# coding: utf-8

# flake8: noqa
"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.author import Author
from openapi_client.models.citation import Citation
from openapi_client.models.contact_information import ContactInformation
from openapi_client.models.error import Error
from openapi_client.models.protein_entry import ProteinEntry
from openapi_client.models.version_entry import VersionEntry
