# coding: utf-8

# flake8: noqa

"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.citation_api import CitationApi
from openapi_client.api.protein_api import ProteinApi
from openapi_client.api.proteins_api import ProteinsApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.author import Author
from openapi_client.models.citation import Citation
from openapi_client.models.contact_information import ContactInformation
from openapi_client.models.error import Error
from openapi_client.models.protein_entry import ProteinEntry
from openapi_client.models.version_entry import VersionEntry
