# coding: utf-8

"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.proteins_api import ProteinsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProteinsApi(unittest.TestCase):
    """ProteinsApi unit test stubs"""

    def setUp(self):
        self.api = ProteinsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_protein_citation(self):
        """Test case for create_protein_citation

        Enter a new protein citation  # noqa: E501
        """
        pass

    def test_create_protein_version(self):
        """Test case for create_protein_version

        Create a new version of this pdb_id  # noqa: E501
        """
        pass

    def test_get_protein(self):
        """Test case for get_protein

        Get the  entry for this pdb_id  # noqa: E501
        """
        pass

    def test_get_protein_citations(self):
        """Test case for get_protein_citations

        Get the all citation entries for this pdb_id  # noqa: E501
        """
        pass

    def test_get_protein_citations_by_version(self):
        """Test case for get_protein_citations_by_version

        Get the all citation entries for this pdb_id version  # noqa: E501
        """
        pass

    def test_list_proteins(self):
        """Test case for list_proteins

        List the pdb ids currently available in the database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
