# coding: utf-8

"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.protein_api import ProteinApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProteinApi(unittest.TestCase):
    """ProteinApi unit test stubs"""

    def setUp(self):
        self.api = ProteinApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_protein(self):
        """Test case for create_protein

        Enter a new protein into the database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
