# coding: utf-8

"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.pdbid import PDBId  # noqa: E501
from swagger_client.rest import ApiException


class TestPDBId(unittest.TestCase):
    """PDBId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPDBId(self):
        """Test PDBId"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.pdbid.PDBId()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
