# coding: utf-8

"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.citation_api import CitationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCitationApi(unittest.TestCase):
    """CitationApi unit test stubs"""

    def setUp(self):
        self.api = CitationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_proteins_cited(self):
        """Test case for get_proteins_cited

        Get all proteins cited by this article  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
