# coding: utf-8

"""
    Protein Version Citation API 

    An API for looking at literature which cites a given protein version   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProteinEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pdb_id': 'int',
        'versions': 'list[VersionEntry]'
    }

    attribute_map = {
        'pdb_id': 'pdb_id',
        'versions': 'versions'
    }

    def __init__(self, pdb_id=None, versions=None):  # noqa: E501
        """ProteinEntry - a model defined in Swagger"""  # noqa: E501
        self._pdb_id = None
        self._versions = None
        self.discriminator = None
        if pdb_id is not None:
            self.pdb_id = pdb_id
        self.versions = versions

    @property
    def pdb_id(self):
        """Gets the pdb_id of this ProteinEntry.  # noqa: E501


        :return: The pdb_id of this ProteinEntry.  # noqa: E501
        :rtype: int
        """
        return self._pdb_id

    @pdb_id.setter
    def pdb_id(self, pdb_id):
        """Sets the pdb_id of this ProteinEntry.


        :param pdb_id: The pdb_id of this ProteinEntry.  # noqa: E501
        :type: int
        """

        self._pdb_id = pdb_id

    @property
    def versions(self):
        """Gets the versions of this ProteinEntry.  # noqa: E501


        :return: The versions of this ProteinEntry.  # noqa: E501
        :rtype: list[VersionEntry]
        """
        return self._versions

    @versions.setter
    def versions(self, versions):
        """Sets the versions of this ProteinEntry.


        :param versions: The versions of this ProteinEntry.  # noqa: E501
        :type: list[VersionEntry]
        """
        if versions is None:
            raise ValueError("Invalid value for `versions`, must not be `None`")  # noqa: E501

        self._versions = versions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProteinEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProteinEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
